web:
  restart: always
  build ./web
  expose:
    - "8000"
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:pp

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static

data:
  restart: always
  image: mariadb:mariadb
